### PR TITLE
Update to NetStandard and latest pre xamarin forms

### PR DESCRIPTION
**Pull request by mikescandy**
I updated the portable projects to NetStandard 2.0 and reference the latest prerelease of Xamarin forms 2.4 (should be stable soon, hopefully).
Maybe this PR could lead to a new -pre version.

### CODE REVIEW

**Comment by tomh4** [comment]
hey,are the badges working for you ? I´m getting this error :
`Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

**Comment by CarnageMarkus** [comment]
@mikescandy Hi, have you thought about uploading new nuget yourself ? This repo seems dead

**Comment by mikescandy** [comment]
not really, i'll have to rebuild it against 2.5 first and see what happens. Honestly, I'd like to move to the android support bottom navigation bar, so i'm not sure if i want to rely on this for the long term.

**Comment by Nixon-Joseph** [comment]
Hey, is there any way you could figure out why I'm getting this error?
`System.TypeInitializationException: The type initializer for 'Attribute' threw an exception.`
If I walk through my code, it's happening on a line of code:
`await ProgressBar.ProgressTo(value, 150, Easing.SinOut);`.
I can't seem to pinpoint it any further. No context or stack trace or detailed message or anything.
Running in 2.5.0.122203.

Also what do you mean by your last comment "I'd like to move to the android support bottom navigation bar"? Is this a thing already? I can't find any references to it.

**Comment by swapnil591** [comment]
Failed to resolve assembly: 'BottomBar.XamarinForms, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
How to solve this issue

**Comment by juanagu** [comment]
@DominicFrei  @sschmidt

**Comment by peacecwz** [comment]
Really is there anyone looking this repo? @sschmidt

**Comment by mikescandy** [comment]
honestly, have a look at the Xamarin.Forms botton navigation tab (I largely implemented it...)

**Comment by peacecwz** [comment]
@mikescandy Is it offical support? Now I have ssen it. Thanks

**Comment by mikescandy** [comment]
I'm going to close this.

**Pull request closed without merging**
