### PR TITLE
XAML Support and other fixes

### PR DESCRIPTION
**Pull request by lholota**
Hi, 
I'm trying to use the lib in one of my projects and I've hit some small issues, so I'm sending fixes :)

- The TabColor property can now be set in XAML (fixed the attached property definition), I also added an example for pure XAML definition
- Bug fix - when the CurrentPage was changed directly from code by setting the CurrentPage property, the content was changed, but the selected tab in the bottom bar didn't

I am also trying to get the page working with Prism navigation, but that seems to be a bit tougher than I thought, so maybe later...

### CODE REVIEW

**Comment by lholota** [comment]
Btw. the latest nuget available at nuget.org doesn't seem to contain the latest version (e.g. the BottomBarPage doesn't have the FixedMode property etc.)

**Comment by lazmeister** [comment]
This will resolve our issue too, hopefully, it will be put into the latest!

**Comment by lazmeister** [comment]
Hey @lholota I see you forked the repo, I talked to the owners and we should be able to push through some updates via github

**Comment by lholota** [comment]
Cool :)

**Comment by lazmeister** [comment]
Just waiting on the budget permissions and we should be all set

**Comment by lazmeister** [comment]
Nuget*

**Pull request merged**
