### PR TITLE
Add reference to BottomBar.XamarinForms for shared projects & Update the PCL profiles

### LINKED ISSUE #20: Installing in Blank Xamarin Forms project
Hi there,

I am attempting to install this package using the nuget package manager inside Visual Studio 2015.

However when I install I get the following error message:
`Could not install package 'ThriveGmbH.BottomNavigationBar.XF 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Any help please?

### PR DESCRIPTION
**Pull request by ice-j**
This will fix #20 and #19

### CODE REVIEW

**Comment by DominicFrei** [comment]
@jbucka @escamoteur Any chance you can check @ice-j solution for your two issues?

**Comment by jbucka** [comment]
@dominicfrei is there a new nuget package so that I can try?

**Comment by DominicFrei** [comment]
@sschmidt is that something you can do?

**Comment by Im-PJ** [comment]
Please merge this PR. I'm unable to add this library in shared project.

**Comment by Dids** [comment]
Yes, please merge this asap.

**Comment by DominicFrei** [comment]
Thank you very much for your contribution, ice-j!

**Comment by salmangadit** [comment]
Hi, is there going to be a new nuget package version with this PR merged?

**Comment by Blackbaud-IanThomas** [comment]
@DominicFrei Can we get the update published to the nuget repo?

**Comment by Blackbaud-IanThomas** [comment]
@DominicFrei Any updates on this?

**Comment by bruce-willis** [comment]
@Blackbaud-IanThomas Hello! Can help u with creating local nuget package with last release if u needed

**Comment by Blackbaud-IanThomas** [comment]
@bruce-willis I've been building and using one locally for a while.  Thanks, though.  I just want this to be available from a public nuget feed.

**Pull request merged**
