### PR TITLE
Bottom bar selected icon feature

### LINKED ISSUE #31: Changing the Icon of a Page works on iOS but not Android
If the `Icon` of a `Page`  that is a children of a `BottomBarPage` is changed after instantiation, the change is reflected on the iOS version of the Xamarin Forms app but not on the Android one.

### PR DESCRIPTION
**Pull request by r2d2rigo**
Fixes #31.

### CODE REVIEW

**Comment by lazmeister** [comment]
can you please re-submit?

**Comment by r2d2rigo** [comment]
Hi @lazmeister - currently I'm not actively working on improvements to this library since I built a custom version for a specific project that is feature complete for my needs.

I'll take a look into porting those changes forward when I have more free time, probably in 2-3 weeks.

**Comment by lazmeister** [comment]
okay great thanks, sorry for the notifications, we need to get a dev branch going for these PL's

**Comment by r2d2rigo** [comment]
No worries! This project helped me a lot, the less I can do is contribute back!

**Pull request merged**
